---
title: "Bayesian Enrichment Estimation in R (BEER)"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

BEER is a Bayesian hierarchical model for identifying enriched antibody responses from phage-immunoprecipitation sequencing (PhIP-Seq) data. Here, we introduce the notation and describe the BEER model and implementation in the `R` package [`beer`](https://github.com/athchen/beer). 

## Notation

Let $i = 1, 2, \ldots, P$ and $j = 1, 2, \ldots, 96$ index the peptides and samples, respectively. Without loss of generality, assume samples $\{1, 2, \ldots, N\}$ are mock IP (beads-only) samples. We observe, 

\begin{align*}
Y_{ij} &= \text{ observed # reads mapped to peptide } i \text{ in sample } j\\
n_j &= \sum_{i=1}^P Y_{ij} \text{ total # of reads in sample }j
\end{align*}

Define, 

\begin{align*}
\theta_{ij} &= \text{ probability that peptide } i \text{ in sample } j \text{ pulls a read }\\
Z_{ij} &= \unicode{x1D7D9}(\text{peptide } i \text{ in sample } j \text { is enriched})\\
\pi_{j} &= \text{ proportion of enriched peptides in sample } j\\
c_j &= \text{ attenuation constant for sample } j\\
\phi_{ij} &= \text{ true fold change of peptide } i \text{ in sample } j
\end{align*}

Prior parameters for $\theta_{ij}, \pi_j, c_j$, and $\phi_{ij}$ are denoted by, 

\begin{align*}
a_{ij}, b_{ij} &= \text{ shape parameters for the prior distribution of } \theta_{ij} \text{ for peptide } i \text{ in sample } j\\
a_{\pi}, b_{\pi} &= \text{ shape parameters for the prior distribution of } \pi_{j}\\
a_c, b_c &= \text{ shape parameters for the prior distribution of } c_{j}\\
a_\phi, b_\phi &= \text{ shape parameters for the prior distribution of } \phi_{ij}|Z_{ij} = 1
\end{align*}

Parameters specific to beads-only samples are denoted with the subscript $i0$ (e.g. $a_{i0}, b_{i0}, \theta_{i0}$, etc.). Additionally, let $\phi_{min}$ denote the minimum fold-change for an enriched peptide. 

For convenience, we also define two function $f_a, f_b$ for deriving Beta parameters $a, b$ given mean $\mu$ and variance $\sigma^2$: 

\begin{align*}
f_a(\mu, \sigma^2) &= \frac{\mu^2(1-\mu)}{\sigma^2} - \mu\\
f_b(\mu, \sigma^2) &= f_a(\mu, \sigma^2) \left(\frac{1}{\mu} - 1\right)
\end{align*}

## Model

Let $\mu_{i0}$ and $\sigma^2_{i0}$ denote the mean and variance for peptide $i$ in a beads-only sample where, 

\begin{align*}
\mu_{ij} &= \frac{a_{i0}}{a_{i0} + b_{i0}}\\
\sigma^2_{i0} &= \frac{a_{i0}b_{i0}}{(a_{i0} + b_{i0})^2 (a_{i0} + b_{i0} + 1)}.
\end{align*}

To infer reactivity, we compare one sample to all beads-only samples on the same plate. Our hierarchical model given a sample $j \in \{N+1, \ldots, 96\}$ is described as follows.

\begin{align*}
    Y_{ij}|\theta_{ij} &\sim \text{Binomial}(n_j, \theta_{ij}) \\
    \theta_{ij}|a_{i0}, b_{i0}, c_j, \phi_{ij} &\sim \text{Beta}(f_a(c_j \phi_{ij} \mu_{i0}, \sigma^2_{i0}), f_b(c_j \phi_{ij} \mu_{i0}, \sigma^2_{i0})) \\
%    c_j|B_j & \sim B_j\cdot 1 + (1 - B_j) \cdot \text{Beta}(a_c, b_c) \\
    c_j & \sim \text{Beta}(a_c, b_c) \\
    \phi_{ij}|Z_{ij} & \sim (1 - Z_{ij}) \cdot 1 + Z_{ij}(\phi_{min} + \text{Gamma}(a_\phi, b_\phi)) \\
    Z_{ij}|\pi_j & \sim \text{Bernoulli}(\pi_j)\\
    \pi_j &\sim \text{Beta}(a_\pi, b_\pi) 
\end{align*}

## Prior parameters

### Figure S16

**Left:** the prior distribution for the proportion of reactive peptides in sample $j$, $\pi_j$, modeled as a Beta distribution Beta($a_\pi$ = 2, $b_\pi$ = 300), reflecting peptide enrichment seen in previous studies.
**Middle:** a Gamma($a_\phi$ = 1.25, $b_\phi$ = 0.1) distribution, used in the prior distribution for the fold change $\phi_{ij}$ for peptide $i$ in sample $j$, if reactive.
**Right:** the prior distribution for the scaling constant in sample $j$, $c_j$, modeled as a Beta distribution Beta($a_c = 80$, $b_c = 20$).

```{r priors, fig.width = 10, fig.height = 4}
par(mfrow = c(1,3),las=1,yaxs="i",mar=c(5,1,3,1),cex.axis=1.3)
curve(dbeta(x,2,300),from=0,to=0.05,n=501,
      xlab="",ylab="",yaxt="n",ylim=c(0,115),lwd=3,col="red")
curve(dgamma(x,1.25,0.1),from=0,to=80,n=501,
      xlab="",ylab="",yaxt="n",ylim=c(0,0.065),lwd=3,col="blue")
curve(dbeta(x,80,20),from=0.5,to=1,n=501,
      xlab="",ylab="",yaxt="n",ylim=c(0,10.5),lwd=3,col="green3")
```
## Implementation

To reduce computational time, BEER runs each sample individually in comparison to all beads-only samples and removes clearly enriched peptides apriori. The implementation can be broken down into the following steps: 

1. **Define prior parameters.** Though most prior parameters are supplemented by the user (or use the defaults), prior parameters for non-enriched peptides are first approximated using all beads-only samples.
2. **Identify super enriched peptides.** Based on the prior parameters, super enriched peptides are first excluded as these peptides should always have posterior probabilities of enrichment of 1.
3. **Re-estimate beads-only prior parameters.** Prior parameters are then reestimated from the beads-only samples for the remaining peptides.
4. **Initialize and run the MCMCs.** To reduce convergence time, MLE estimates are used to initialize the MCMC sampler, and samples are drawn from the posterior distributions of the unknown parameters.
5. **Summarize and store results.** Posterior samples are summarized using the means of the posterior distribution and are stored in the PhIPData object.

For more information, please see the _Supplemental Methods_ section of the manuscript. 


